'use client';
import {useState} from 'react';
import {UserRound,KeyRound,LogOut,Copy,Plus,Loader2,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {sessionFetch} from '@/lib/auth-client';
import type {AuthUser,InviteSummary,MemberSummary} from '@/lib/auth-types';
function Choose({value,items,label,change}:{value:string;items:string[];label:string;change:(value:string)=>void}){return <Select value={value} onValueChange={v=>v&&change(v)}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
const date=(value:number)=>new Date(value).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'});
export default function AccountControls({user,onChanged,onLogout}:{user:AuthUser;onChanged:()=>Promise<void>;onLogout:()=>Promise<void>}){
const [account,setAccount]=useState(false),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState('');
const [name,setName]=useState(user.displayName),[oldPassword,setOldPassword]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
const [invites,setInvites]=useState<InviteSummary[]>([]),[members,setMembers]=useState<MemberSummary[]>([]),[newCode,setNewCode]=useState(''),[label,setLabel]=useState(''),[days,setDays]=useState('7 天'),[uses,setUses]=useState('1 人'),[tab,setTab]=useState('invites');
async function request(url:string,body:unknown){const r=await sessionFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string;code?:string};if(!r.ok)throw new Error(data.error);return data}
async function refresh(){setLoading(true);try{const r=await sessionFetch('/api/invites');const data=await r.json() as {error?:string;invites:InviteSummary[];members:MemberSummary[]};if(!r.ok)throw new Error(data.error);setInvites(data.invites);setMembers(data.members)}catch(e){setError(e instanceof Error?e.message:'暂时无法加载')}finally{setLoading(false)}}
async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setFeedback('');try{await action()}catch(e){setError(e instanceof Error?e.message:'操作没有成功，请重试')}finally{setBusy(false)}}
async function create(){await run(async()=>{const data=await request('/api/invites',{action:'create',label,days:parseInt(days),maxUses:parseInt(uses)});setNewCode(data.code||'');setLabel('');await refresh()})}
async function copy(){try{await navigator.clipboard.writeText(newCode);setFeedback('已复制邀请码。')}catch{setFeedback('浏览器没有开放复制权限，请选中上方邀请码手动复制。')}}
return <><button className="account-button" onClick={()=>{setAccount(true);setName(user.displayName);setError('');setFeedback('')}}><span className="account-avatar">{user.displayName.slice(0,1)}</span><span><strong>{user.displayName}</strong><small>{user.role==='admin'?'站点管理员':'我的账号'} · @{user.username}</small></span><UserRound size={16}/></button>{user.role==='admin'&&<button className="quiet-button" onClick={()=>{setManage(true);setError('');setFeedback('');void refresh()}}><KeyRound size={17}/> 邀请码管理</button>}
<Dialog open={account} onOpenChange={open=>{setAccount(open);if(!open){setOldPassword('');setPassword('');setConfirm('');setError('');setFeedback('')}}}><DialogContent className="settings-dialog account-dialog"><DialogHeader><DialogTitle>我的小账号</DialogTitle><DialogDescription>@{user.username} · {user.role==='admin'?'管理员':'学习伙伴'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run(async()=>{await request('/api/auth',{action:'profile',displayName:name});await onChanged();setFeedback('昵称已更新。')})}} className="auth-form"><label htmlFor="account-name">昵称<Input id="account-name" value={name} onChange={e=>setName(e.target.value)} maxLength={24} required/></label><button type="submit" className="secondary-button" disabled={busy}>保存昵称</button></form><div className="account-divider"/><form className="auth-form" onSubmit={e=>{e.preventDefault();if(password!==confirm){setError('两次新密码不一致。');return}void run(async()=>{await request('/api/auth',{action:'password',currentPassword:oldPassword,password});setOldPassword('');setPassword('');setConfirm('');setFeedback('密码已更新，其他设备的登录已退出。')})}}><h3>换一个新密码</h3><input type="text" autoComplete="username" value={user.username} className="sr-only" readOnly tabIndex={-1}/><label htmlFor="current-password">当前密码<Input id="current-password" type="password" autoComplete="current-password" value={oldPassword} onChange={e=>setOldPassword(e.target.value)} minLength={10} maxLength={128} required/></label><label htmlFor="new-password">新密码<Input id="new-password" type="password" autoComplete="new-password" placeholder="10—128 个字符" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} maxLength={128} required/></label><label htmlFor="repeat-password">确认新密码<Input id="repeat-password" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10} maxLength={128} required/></label><button type="submit" className="primary-button" disabled={busy}>{busy?'正在处理…':'更新密码'}</button></form>{error&&<p className="auth-error" role="alert">{error}</p>}{feedback&&<p className="auth-feedback" role="status">{feedback}</p>}<button className="quiet-button logout-button" disabled={busy} onClick={()=>void run(onLogout)}><LogOut size={17}/> 退出当前账号</button></DialogContent></Dialog>
<Dialog open={manage} onOpenChange={open=>{setManage(open);if(!open){setNewCode('');setError('');setFeedback('')}}}><DialogContent className="invite-dialog"><DialogHeader><span className="invite-kicker"><ShieldCheck size={17}/> 管理员的小工具</span><DialogTitle>邀请学习伙伴</DialogTitle><DialogDescription>把邀请码交给信任的人。每个人都拥有自己的进度、收藏和复盘。</DialogDescription></DialogHeader><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="resource-tabs"><TabsTrigger value="invites">邀请码</TabsTrigger><TabsTrigger value="members">已注册伙伴 · {members.length}</TabsTrigger></TabsList><TabsContent value="invites"><form className="invite-create" onSubmit={e=>{e.preventDefault();void create()}}><label htmlFor="invite-label">备注<Input id="invite-label" placeholder="例如：一起备考的小伙伴" value={label} onChange={e=>setLabel(e.target.value)} maxLength={40}/></label><div className="invite-options"><label>可注册人数<Choose value={uses} items={['1 人','5 人','10 人','20 人','50 人']} label="可注册人数" change={setUses}/></label><label>有效期<Choose value={days} items={['1 天','7 天','30 天']} label="邀请码有效期" change={setDays}/></label><button type="submit" className="primary-button" disabled={busy||!!newCode}><Plus size={17}/>生成邀请码</button></div></form>{newCode&&<div className="new-invite"><strong>这份小邀请，准备好了</strong><label htmlFor="generated-code" className="sr-only">新生成的邀请码</label><Input id="generated-code" value={newCode} readOnly onFocus={e=>e.target.select()}/><p>完整邀请码只展示这一次，关闭前记得复制。</p><div><button className="secondary-button" onClick={()=>void copy()}><Copy size={15}/> 复制邀请码</button><button className="text-button" onClick={()=>{setNewCode('');setFeedback('')}}>已经保存好了</button></div></div>}<div className="invite-list">{loading&&<p className="auth-feedback"><Loader2 className="spinning" size={16}/>正在读取邀请记录…</p>}{!loading&&invites.length===0&&<p className="empty-state">还没有邀请记录，先生成一份小邀请吧。</p>}{invites.map(i=>{const status=i.revoked?'已停用':i.expiresAt<=Date.now()?'已过期':i.used>=i.maxUses?'已用完':'可使用';return <article className="invite-row" key={i.id}><div><strong>{i.label}</strong><small>{i.prefix} · {i.used}/{i.maxUses} 人已注册 · {date(i.expiresAt)} 到期</small></div><span className={'tag '+(status==='可使用'?'tag-green':'tag-peach')}>{status}</span>{status==='可使用'&&<button disabled={busy} onClick={()=>void run(async()=>{await request('/api/invites',{action:'revoke',id:i.id});await refresh();setFeedback('邀请码已停用，已注册账号不受影响。')})}>停用</button>}</article>})}</div></TabsContent><TabsContent value="members"><div className="member-list">{members.map(m=><article key={m.id}><span className="account-avatar">{m.displayName.slice(0,1)}</span><div><strong>{m.displayName}</strong><small>@{m.username} · {date(m.createdAt)} 加入</small></div><span className="tag tag-green">{m.role==='admin'?'管理员':'学习伙伴'}</span></article>)}</div></TabsContent></Tabs>{error&&<p className="auth-error" role="alert">{error}</p>}{feedback&&<p className="auth-feedback" role="status">{feedback}</p>}</DialogContent></Dialog></>
}

