'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Home,Route,Library,BookOpen,NotebookPen,ArrowUpRight,ArrowRight,Sparkles,Clock3,Settings2,Leaf,Check,RefreshCw,Bookmark,Search,ChevronLeft,ChevronRight,ExternalLink,CheckCircle2,Loader2,X,Cloud,Heart} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Textarea} from '@/components/ui/textarea';
import {defaultProfile,initialResources,lessons,lessonById,planFor,stages,stageOf,todayCN,type Profile,type Resource,type Task,type Lesson} from '@/lib/study-data';
type View='today'|'plan'|'resources'|'lessons'|'notes';
type Note={id:string;subject:string;text:string;createdAt:string};
type Answer={id:string;choice:number;correct:number};
type Collection={at:string;added:number;sources:{source:string;url:string;status:string;message:string;found:number;added:number}[]};
type State={profile:Profile;progress:string[];resources:Resource[];bookmarks:string[];notes:Note[];answers:Answer[];collection:Collection|null};
const nav:{id:View;icon:typeof Home;label:string}[]=[{id:'today',icon:Home,label:'今天学什么'},{id:'plan',icon:Route,label:'30 天上岸路线'},{id:'resources',icon:Library,label:'资料补给站'},{id:'lessons',icon:BookOpen,label:'一口小课堂'},{id:'notes',icon:NotebookPen,label:'我的复盘本'}];
const stamp=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
function Choice({value,items,onChange,label}:{value:string;items:string[];onChange:(s:string)=>void;label:string}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>}
function Navigation({view,go}:{view:View;go:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-item" isActive={view===n.id} onClick={()=>{go(n.id);setOpenMobile(false)}}><n.icon/><span>{n.label}</span>{view===n.id&&<span className="tiny-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
export default function StudyApp(){
const [view,setView]=useState<View>('today'),[state,setState]=useState<State>({profile:defaultProfile(),progress:[],resources:initialResources,bookmarks:[],notes:[],answers:[],collection:null});
const [loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[collecting,setCollecting]=useState(false);
const [day,setDay]=useState(1),[settingsOpen,setSettingsOpen]=useState(false),[draft,setDraft]=useState(defaultProfile()),[activeLesson,setActiveLesson]=useState<Lesson|null>(null),[activeTask,setActiveTask]=useState<Task|null>(null),[choice,setChoice]=useState<number|null>(null),[revealed,setRevealed]=useState(false);
const [category,setCategory]=useState('全部资料'),[query,setQuery]=useState(''),[subject,setSubject]=useState('全部科目'),[year,setYear]=useState('全部年份'),[stage,setStage]=useState('0'),[showSources,setShowSources]=useState(false);
const [noteText,setNoteText]=useState(''),[noteSubject,setNoteSubject]=useState('学习复盘');
const loadingRef=useRef(false),busyRef=useRef(false),saveBusy=useRef(false);
const go=useCallback((v:View)=>{setView(v);window.location.hash=v;window.scrollTo({top:0,behavior:'instant'})},[]);
const load=useCallback(async(initial=false)=>{if(loadingRef.current)return;loadingRef.current=true;try{const r=await fetch('/api/state');const s=await r.json() as State & {error?:string};if(!r.ok)throw new Error(s.error);setState(prev=>initial?s:{...prev,resources:s.resources,collection:s.collection});setLoaded(true);setLoadError('');if(initial){const d=Math.max(1,Math.min(30,Math.floor((Date.parse(todayCN())-Date.parse(s.profile.startDate))/86400000)+1));setDay(d);setStage(String(stageOf(d)))}}catch(e){setLoadError(e instanceof Error?e.message:'暂时无法读取，请重试')}finally{loadingRef.current=false}},[]);
const collect=useCallback(async(force=false)=>{if(busyRef.current)return;busyRef.current=true;setCollecting(true);try{const r=await fetch('/api/collect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force})});const data=await r.json() as {error?:string;report:Collection|null;busy?:boolean;skipped?:boolean};if(!r.ok)throw new Error(data.error);if(data.report)setState(s=>({...s,collection:data.report}));if(force)setMessage(data.busy?'资料正在收集中，稍后再看看。':data.skipped?'刚刚已经检查过啦。手动收集每 5 分钟可进行一次。':'这次新增 '+(data.report?.added||0)+' 条资料。各来源结果可在“收集记录”查看。');await load()}catch(e){if(force)setMessage(e instanceof Error?e.message:'收集没有完成，请稍后重试')}finally{busyRef.current=false;setCollecting(false)}},[load]);
useEffect(()=>{void load(true);const sync=()=>{const hash=window.location.hash.slice(1);if(nav.some(n=>n.id===hash))setView(hash as View)};sync();window.addEventListener('hashchange',sync);return ()=>window.removeEventListener('hashchange',sync)},[load]);
useEffect(()=>{if(!loaded)return;void collect();const timer=setInterval(()=>void collect(),3600000);return()=>clearInterval(timer)},[loaded,collect]);
async function mutate(payload:unknown){if(saveBusy.current||!loaded)return null;saveBusy.current=true;setSaving(true);try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as {error?:string;ok?:boolean;note?:Note;correct?:boolean};if(!r.ok)throw new Error(data.error);return data}catch(e){setMessage(e instanceof Error?e.message:'没有保存成功，请重试');return null}finally{saveBusy.current=false;setSaving(false)}}
async function toggleTask(id:string){const done=!state.progress.includes(id);if(await mutate({type:'progress',id,done})){setState(s=>({...s,progress:done?[...s.progress,id]:s.progress.filter(x=>x!==id)}));if(done)setMessage('又完成一小步，给自己一个肯定。')}}
async function bookmark(id:string){const done=!state.bookmarks.includes(id);if(await mutate({type:'bookmark',id,done}))setState(s=>({...s,bookmarks:done?[...s.bookmarks,id]:s.bookmarks.filter(x=>x!==id)}))}
function openLesson(id:string,task:Task|null=null){setActiveLesson(lessonById(id));setActiveTask(task);setChoice(null);setRevealed(false)}
function openSettings(){setDraft({...state.profile});setSettingsOpen(true)}
async function saveSettings(){if(await mutate({type:'profile',value:draft})){setState(s=>({...s,profile:draft}));setDay(Math.max(1,Math.min(30,Math.floor((Date.parse(todayCN())-Date.parse(draft.startDate))/86400000)+1)));setSettingsOpen(false);setMessage('备考设置已保存。每天的任务时长会跟着调整。')}}
async function saveNote(){const result=await mutate({type:'note',subject:noteSubject,text:noteText});if(result?.note){const note=result.note;setState(s=>({...s,notes:[note,...s.notes]}));setNoteText('');setMessage('小小复盘已收好，下次再来看看。')}}
async function answer(){if(!activeLesson||choice===null)return;const result=await mutate({type:'answer',id:activeLesson.id,choice});if(result){setRevealed(true);setState(s=>({...s,answers:[...s.answers.filter(a=>a.id!==activeLesson.id),{id:activeLesson.id,choice,correct:result.correct?1:0}]}))}}
const p=state.profile,plan=planFor(day,p.hours),doneToday=plan.tasks.filter(t=>state.progress.includes(t.id)).length,completedDays=Array.from({length:30},(_,i)=>i+1).filter(d=>[0,1,2].every(i=>state.progress.includes(d+'-'+i))).length;
const filtered=state.resources.filter(r=>(category==='全部资料'||category==='我的收藏'?category!=='我的收藏'||state.bookmarks.includes(r.id):r.kind===category)&&(subject==='全部科目'||r.subject===subject)&&(year==='全部年份'||r.year===year)&&(!query||(r.title+' '+r.source+' '+r.summary).toLowerCase().includes(query.toLowerCase())));
const years=['全部年份',...Array.from(new Set(state.resources.map(r=>r.year))).sort().reverse()];
const totalMinutes=plan.tasks.reduce((n,t)=>n+t.minutes,0),wrong=state.answers.filter(a=>!a.correct);
function resourceCard(r:Resource){return <article className="library-card" key={r.id}><div className="flex justify-between gap-3"><div className="resource-tags"><span className={'tag '+(r.kind==='官方信息'?'tag-green':r.kind==='历年真题'?'tag-blue':'tag-peach')}>{r.kind}</span><span>{r.subject} · {r.year}</span></div><button className={'icon-button '+(state.bookmarks.includes(r.id)?'is-saved':'')} aria-label={(state.bookmarks.includes(r.id)?'取消收藏：':'收藏：')+r.title} disabled={!loaded||saving} onClick={()=>void bookmark(r.id)}><Bookmark size={19} fill={state.bookmarks.includes(r.id)?'currentColor':'none'}/></button></div><a className="resource-title" href={r.url} target="_blank" rel="noopener noreferrer">{r.title}<ArrowUpRight size={17}/></a><p>{r.summary}</p><div className="resource-meta"><span>{r.source}</span><span>{r.origin}</span></div><a className="source-link" href={r.url} target="_blank" rel="noopener noreferrer">去来源站阅读 <ExternalLink size={14}/></a></article>}
return <SidebarProvider style={{'--sidebar-width':'15rem'} as React.CSSProperties}><Sidebar><SidebarHeader className="brand"><span className="brand-mark"><Leaf/></span><strong>软软上岸<small>我的 30 天考公小站</small></strong></SidebarHeader><SidebarContent className="side-content"><p className="eyebrow">一起慢慢变厉害</p><Navigation view={view} go={go}/></SidebarContent><SidebarFooter className="side-bottom"><div className="side-note"><span>🌱</span><strong>不用一口吃成胖子</strong><p>今天学会一点点，<br/>就比昨天更接近岸边。</p></div><button className="quiet-button" onClick={openSettings}><Settings2 size={18}/> 我的备考设置</button><span className="sync-label"><Cloud size={13}/>{loaded?'学习记录已连接':loadError?'记录暂未连接':'正在读取学习记录'}</span></SidebarFooter></Sidebar>
<main className="main-shell"><header className="topbar"><div className="flex items-center gap-2"><SidebarTrigger aria-label="打开学习导航" className="md:hidden"/><span>我的学习空间 <span className="muted"> / {nav.find(n=>n.id===view)?.label}</span></span></div><span className="top-badge"><span className="tiny-dot"/>30 天，一起试试看</span></header><div className="workspace">
{loadError&&<div className="notice error" role="alert"><span>{loadError}</span><button onClick={()=>void load(true)}>重试连接</button></div>}
{message&&<div className="notice" role="status"><span>{message}</span><button aria-label="关闭提示" onClick={()=>setMessage('')}><X size={16}/></button></div>}
{view==='today'&&<><div className="greeting"><div><p className="eyebrow">A LITTLE PROGRESS, EVERY DAY</p><h1>今天也要，轻轻努力一下 ☀️</h1><p>{completedDays===30?'30 天的每一步都收好啦。带着你的进步，继续往前走。':p.startDate>todayCN()?'计划从 '+p.startDate+' 开始，今天可以提前认识一下考试。':'从一小步开始就好。你的第 '+day+' 天，准备好啦。'}</p></div><button className="secondary-button" onClick={openSettings}>{p.province||p.target} · 每天 {p.hours} 小时 <Settings2 size={16}/></button></div>
<div className="dashboard-grid"><section className="today-card"><div className="section-heading"><span className="pill">DAY {String(day).padStart(2,'0')} / 30</span><div className="day-controls"><button aria-label="前一天" disabled={day===1} onClick={()=>setDay(day-1)}><ChevronLeft size={17}/></button><span>第 {stageOf(day)+1} 阶段</span><button aria-label="后一天" disabled={day===30} onClick={()=>setDay(day+1)}><ChevronRight size={17}/></button></div></div><h2>{plan.title}</h2><p>{day===1?'今天不追求高分。先摸清题型，知道力气往哪里使。':stages[stageOf(day)].desc}</p><div className="task-list">{plan.tasks.map((t,i)=><div className={'task-row '+(state.progress.includes(t.id)?'done':'')} key={t.id}><Checkbox className="task-check" checked={state.progress.includes(t.id)} disabled={!loaded||saving} onCheckedChange={()=>void toggleTask(t.id)} aria-label={'完成任务：'+t.title}/><button className="task-open" onClick={()=>openLesson(t.lesson,t)}><span className="task-copy"><strong>{t.title}</strong><small>{t.detail}</small></span><span className="task-time"><Clock3 size={14}/>{t.minutes} 分钟</span><ArrowRight size={18}/></button></div>)}</div><div className="card-bottom"><span>今日进度 <b>{doneToday} / 3</b></span><span>{doneToday===3?'今天的努力，已经收好啦 ✓':'预计 '+totalMinutes+' 分钟 · 做完一件，勾一件'}</span></div><Progress value={doneToday/3*100} aria-label="今日任务完成进度"/>{totalMinutes>p.hours*60&&<p className="micro-note">模考保留本科完整时长；准备和复盘可移到相邻一天。省考以本省公告时长为准。</p>}</section>
<aside className="right-column"><section className="journey-card"><span className="eyebrow">我的冲刺小旅程</span><h2>30 天，靠近一点点</h2><div className="journey-number">{String(day).padStart(2,'0')}<span>/ 30 天</span></div><Progress value={completedDays/30*100} aria-label="30 天计划完成进度"/><div className="flex justify-between mt-3 text-sm"><span>已完成 {completedDays} 天</span><span>慢慢来，也很快</span></div><button className="text-button" onClick={()=>{setStage(String(stageOf(day)));go('plan')}}>看看完整学习路线 <ArrowUpRight size={17}/></button></section><section className="gentle-note"><span>✦ 给今天的你</span><p>不会的题不是扣分，<br/>是发现了新的提分空间。</p></section></aside></div>
<div className="section-heading lower-heading"><h2>资料补给，已经备好 ✧</h2><button className="text-button" onClick={()=>go('resources')}>去资料补给站 <ArrowRight size={17}/></button></div><div className="resource-preview">{[{color:'blue',kind:'历年真题',title:'先用一套真题认识考试',sub:'行测 · 申论 · 按年份整理',icon:BookOpen},{color:'peach',kind:'经验分享',title:'别人走过的路，借你参考',sub:'QZZN · 公开经验 · 保留出处',icon:NotebookPen},{color:'mint',kind:'官方信息',title:'考试大纲，从这里开始',sub:'考试范围 · 权威来源',icon:Library}].map(r=><button className={'resource-card '+r.color} key={r.kind} onClick={()=>{setCategory(r.kind);setQuery('');go('resources')}}><span className="resource-icon"><r.icon/></span><span className="category">{r.kind}</span><h3>{r.title}</h3><p>{r.sub}</p><ArrowUpRight className="corner-arrow" size={20}/></button>)}</div><div className="collector-line"><RefreshCw size={14} className={collecting?'spinning':''}/><span>{collecting?'小站正在看看有没有新资料…':state.collection?'上次检查 '+stamp(state.collection.at)+' · 本次新增 '+state.collection.added+' 条':'每天首次打开，自动检查公开资料。'}</span><button onClick={()=>{setShowSources(true);go('resources')}}>查看收集记录</button></div></>}
{view==='plan'&&<><div className="greeting"><div><p className="eyebrow">YOUR 30-DAY JOURNEY</p><h1>一条路线，一天一小步 🌿</h1><p>{p.province||p.target} · 公共科目通用路线 · 每天约 {p.hours} 小时。起点：{p.startDate}</p></div><button className="secondary-button" onClick={openSettings}><Settings2 size={16}/> 调整我的节奏</button></div><div className="plan-intro"><Route size={22}/><p>先建立方法，再用真题练习，最后模拟和复盘。政治理论与常识可每天穿插 10—15 分钟，计入当天学习时长。专业科目需另排时间。</p></div><Tabs value={stage} onValueChange={v=>setStage(String(v))}><TabsList className="stage-tabs">{stages.map((s,i)=><TabsTrigger value={String(i)} key={s.name}><span>0{i+1}<strong>{s.name}</strong><small>{s.range}</small></span></TabsTrigger>)}</TabsList>{stages.map((s,i)=><TabsContent value={String(i)} key={s.name}><div className="plan-days">{Array.from({length:30},(_,k)=>k+1).filter(d=>stageOf(d)===i).map(d=>{const dp=planFor(d,p.hours),n=dp.tasks.filter(t=>state.progress.includes(t.id)).length;return <button key={d} className={'plan-day '+(d===day?'selected':'')+(n===3?' complete':'')} onClick={()=>{setDay(d);go('today')}}><span className="plan-day-num">{n===3?<CheckCircle2 size={23}/>:String(d).padStart(2,'0')}</span><span><strong>{dp.title}</strong><small>{dp.tasks.map(t=>t.minutes).reduce((a,b)=>a+b,0)} 分钟 · {n}/3 已完成</small></span><ArrowRight size={18}/></button>})}</div></TabsContent>)}</Tabs><p className="micro-note">本站编排的冲刺建议，不是官方教学大纲或成绩承诺。遇到模考日，优先保留该科正式时长，可将复盘移到次日。</p></>}
{view==='resources'&&<><div className="greeting"><div><p className="eyebrow">A LITTLE LEARNING PANTRY</p><h1>资料补给站 📚</h1><p>真题找对卷，经验挑着看。把精力留给真正的学习。</p></div><button className="primary-button" disabled={collecting||!loaded} onClick={()=>void collect(true)}><RefreshCw size={17} className={collecting?'spinning':''}/>{collecting?'正在收集…':'帮我收集新资料'}</button></div><div className="collection-panel"><div className="flex gap-3 items-start"><span className="collect-symbol"><Sparkles size={21}/></span><div><strong>每天首次打开，资料自己来补充</strong><p>检查已配置的公开来源，收录标题和原文链接，自动去重。关闭网站后不在后台抓取。登录或付费内容请到原站查看。</p><span className="sync-label">{state.collection?'最近检查：'+stamp(state.collection.at)+' · 新增 '+state.collection.added+' 条':'还没有收集记录，精选入口已先备好。'}</span></div></div><button className="text-button" onClick={()=>setShowSources(!showSources)}>{showSources?'收起记录':'收集记录'} <ArrowUpRight size={16}/></button></div>
{showSources&&<div className="source-report">{state.collection?state.collection.sources.map(s=><div className="source-row" key={s.source}><span className={'source-status '+s.status}>{s.status==='ok'?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}</span><div><a href={s.url} target="_blank" rel="noopener noreferrer">{s.source} <ExternalLink size={12}/></a><p>{s.message}</p></div><b>+{s.added}</b></div>):<p>首次自动检查尚未结束。已有精选资料可以先读。</p>}<p className="micro-note">自动收集不代表内容审核。手动检查间隔 5 分钟；访问受限时保留原文入口，下次再试。</p></div>}
<Tabs value={category} onValueChange={v=>setCategory(String(v))}><TabsList className="resource-tabs">{['全部资料','历年真题','官方信息','经验分享','我的收藏'].map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList>{['全部资料','历年真题','官方信息','经验分享','我的收藏'].map(c=><TabsContent value={c} key={c}><div className="filter-row"><div className="search-box"><Search size={18}/><Input aria-label="搜索资料标题、来源或省份" placeholder="搜真题、科目、年份或省份…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice value={subject} items={['全部科目','行测','申论','综合']} onChange={setSubject} label="筛选科目"/><Choice value={year} items={years} onChange={setYear} label="筛选年份"/></div><div className="results-label"><span>找到 {filtered.length} 份资料</span>{p.province&&<button onClick={()=>setQuery(p.province)}>查找{p.province}资料</button>}</div><div className="library-grid">{filtered.map(resourceCard)}</div>{!filtered.length&&<div className="empty-state"><BookOpen size={30}/><h3>{category==='我的收藏'?'小书架还空着':'还没找到这类资料'}</h3><p>{category==='我的收藏'?'点资料卡右上角的小书签，就能收进来。':'换个关键词，或清空筛选再看看。'}</p><button className="secondary-button" onClick={()=>{setQuery('');setYear('全部年份');setSubject('全部科目');setCategory('全部资料')}}>看看全部资料</button></div>}</TabsContent>)}</Tabs></>}
{view==='lessons'&&<><div className="greeting"><div><p className="eyebrow">SMALL BITES, BIG LITTLE STEPS</p><h1>一口小课堂 🍵</h1><p>先读一个方法，再跟一个例子。把大知识拆成小口吃。</p></div><span className="soft-badge">{lessons.length} 节入门课 · {lessons.filter(l=>l.question).length} 道原创小练习</span></div><div className="lesson-grid">{lessons.map(l=><button key={l.id} className="lesson-card" onClick={()=>openLesson(l.id)}><span className="lesson-emoji">{l.icon}</span><span className="lesson-label">{l.question?'方法 + 例子 + 一题练习':'方法 + 例子'}</span><h2>{l.name}</h2><p>{l.subtitle}</p><div className="lesson-bottom"><span>{state.answers.find(a=>a.id===l.id)?.correct?'✓ 小练习已掌握':'读懂一个小知识'}</span><ArrowRight size={18}/></div></button>)}</div></>}
{view==='notes'&&<><div className="greeting"><div><p className="eyebrow">MAKE MISTAKES, MAKE PROGRESS</p><h1>我的复盘本 📒</h1><p>把“我不会”换成“我知道下次怎么做”。</p></div><span className="soft-badge">{state.notes.length} 条笔记 · {wrong.length} 道待回看练习</span></div><div className="notes-grid"><section className="note-editor"><h2>今天，收获了一点什么？</h2><p>可以按「题目 / 错在哪里 / 下次先做什么」写。</p><Choice value={noteSubject} items={['学习复盘',...lessons.map(l=>l.name)]} onChange={setNoteSubject} label="笔记科目"/><Textarea aria-label="复盘笔记" placeholder="比如：增长率分母又用错啦。下次先圈出“去年”，写好基期再算。" value={noteText} onChange={e=>setNoteText(e.target.value)} maxLength={4000}/><div className="flex justify-between items-center"><span className="muted text-sm">{noteText.length}/4000</span><button className="primary-button" disabled={!noteText.trim()||!loaded||saving} onClick={()=>void saveNote()}><Check size={16}/>收好这条笔记</button></div></section><section className="review-guide"><span>✦ 复盘的三个小问题</span><ol><li>这道题到底在问什么？</li><li>我卡在知识、方法，还是读题？</li><li>下次遇到它，第一步做什么？</li></ol><p>明天、三天后、一周后，回来独立做一遍。</p></section></div>
{wrong.length>0&&<><div className="section-heading lower-heading"><h2>这些小练习，再见一面</h2></div><div className="wrong-list">{wrong.map(a=>{const l=lessonById(a.id);return <button className="wrong-card" key={a.id} onClick={()=>openLesson(a.id)}><span>{l.icon}</span><div><strong>{l.name}</strong><p>{l.question?.text}</p></div><ArrowRight size={18}/></button>})}</div></>}
<div className="section-heading lower-heading"><h2>留给未来自己的小纸条</h2><span className="muted text-sm">{state.notes.length} 条</span></div>{state.notes.length?<div className="saved-notes">{state.notes.map(n=><article key={n.id}><div><span className="tag tag-green">{n.subject}</span><span>{stamp(n.createdAt)}</span></div><p>{n.text}</p></article>)}</div>:<div className="empty-state"><NotebookPen size={29}/><p>这里还没有笔记。今天的小发现，值得留一行。</p></div>}</>}
<p className="footnote"><Heart size={14}/>30 天是冲刺周期，按自己的基础调整。每一小步都算数。</p>
</div></main>
<Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>找到你舒服的学习节奏</DialogTitle><DialogDescription>按当前基础与空闲时间调整，已经完成的任务会保留。</DialogDescription></DialogHeader><div className="settings-field"><label>考试目标</label><Choice label="考试目标" value={draft.target} items={['通用备考','国考','省考']} onChange={target=>setDraft(d=>({...d,target,province:target==='省考'?d.province:''}))}/></div>{draft.target==='省考'&&<div className="settings-field"><label htmlFor="province">省份</label><Input id="province" value={draft.province} maxLength={20} placeholder="例如：广东" onChange={e=>setDraft(d=>({...d,province:e.target.value}))}/><small>用于资料检索；课程与路线覆盖公共科目通用方法。</small></div>}<div className="settings-field"><label>每天学习时间</label><Choice label="每天学习时间" value={draft.hours+' 小时'} items={['2 小时','3 小时','4 小时','6 小时']} onChange={v=>setDraft(d=>({...d,hours:parseInt(v)}))}/></div><div className="settings-field"><label htmlFor="start-date">30 天计划开始日期</label><Input id="start-date" type="date" value={draft.startDate} onChange={e=>setDraft(d=>({...d,startDate:e.target.value}))}/></div><p className="micro-note">计划覆盖行测与申论，不含岗位专业科目。模考日需保留正式时长，可把复盘移到次日。</p><button className="primary-button" disabled={!loaded||saving||!draft.startDate} onClick={()=>void saveSettings()}>{saving?'正在保存…':'就按这个节奏来'}</button></DialogContent></Dialog>
<Dialog open={!!activeLesson} onOpenChange={open=>{if(!open){setActiveLesson(null);setActiveTask(null)}}}><DialogContent className="lesson-dialog">{activeLesson&&<><DialogHeader><span className="lesson-dialog-kicker">{activeLesson.icon} {activeTask?'DAY '+activeTask.id.split('-')[0]+' · '+activeTask.minutes+' 分钟建议':'一口小课堂 · 本站原创讲解'}</span><DialogTitle>{activeTask?.title||activeLesson.name}</DialogTitle><DialogDescription>{activeLesson.subtitle}</DialogDescription></DialogHeader>{activeTask&&<div className="task-instruction"><strong>这一小步怎么做</strong><p>{activeTask.title}。先读下面的方法，再完成练习或去资料站选对应真题。需要写答案时，先独立作答，再对照来源站参考解析。</p></div>}<div className="lesson-reading">{activeLesson.steps.map((s,i)=><section key={s.title}><h3><span>{String(i+1).padStart(2,'0')}</span>{s.title}</h3><p>{s.text}</p></section>)}<div className="worked-example"><strong>🌰 看一个小例子</strong><p>{activeLesson.example}</p></div><div className="takeaway"><Sparkles size={19}/><p>{activeLesson.takeaway}</p></div>
{activeLesson.id==='start'||activeLesson.id==='mock'||activeLesson.id==='politics'?<a className="source-link" href={initialResources[0].url} target="_blank" rel="noopener noreferrer">考试范围与国考时长参考：2026 公共科目笔试大纲 <ExternalLink size={14}/></a>:null}
{activeLesson.question&&<section className="quiz"><div className="section-heading"><h3>试一小题</h3><span className="tag tag-blue">原创入门练习 · 非真题</span></div><p>{activeLesson.question.text}</p><RadioGroup value={choice===null?'':String(choice)} onValueChange={v=>setChoice(Number(v))} disabled={revealed} aria-label="选择一个答案">{activeLesson.question.options.map((o,i)=><label key={o} className={'quiz-option '+(choice===i?'chosen':'')+(revealed&&activeLesson.question?.answer===i?' correct':'')}><RadioGroupItem value={String(i)} aria-label={o}/><span>{String.fromCharCode(65+i)}</span>{o}{revealed&&activeLesson.question?.answer===i&&<Check size={17}/>}</label>)}</RadioGroup>{!revealed?<button className="primary-button" disabled={choice===null||!loaded||saving} onClick={()=>void answer()}>交出我的答案</button>:<div className={'answer-explanation '+(choice===activeLesson.question.answer?'right':'wrong')}><strong>{choice===activeLesson.question.answer?'做对啦，方法正在变顺手。':'没关系，这一步现在弄明白就好。'}</strong><p>{activeLesson.question.explanation}</p><small>{choice!==activeLesson.question.answer?'已加入复盘本，重新作答正确后会移出待回看。':'答题记录已经保存。'}</small><button className="text-button" onClick={()=>{setChoice(null);setRevealed(false)}}>再独立做一次</button></div>}</section>}
</div><div className="lesson-actions"><button className="secondary-button" onClick={()=>{setCategory('历年真题');setSubject(activeLesson.id==='shenlun'?'申论':'全部科目');setQuery('');setActiveLesson(null);go('resources')}}>找对应真题 <ArrowUpRight size={16}/></button>{activeTask&&<button className="primary-button" disabled={!loaded||saving} onClick={()=>void toggleTask(activeTask.id)}><Check size={17}/>{state.progress.includes(activeTask.id)?'已完成 · 取消打卡':'这一小步，完成啦'}</button>}</div></>}</DialogContent></Dialog>
</SidebarProvider>
}

